### ISSUE TITLE
Checkpoint takes precedence over next level

### ISSUE THREAD

**Issue by eneb** [increpare/PuzzleScript#316]
If a checkpoint is set and then the level is won, instead of loading any future levels Puzzlescript just restarts from the checkpoint.

See e.g. http://www.puzzlescript.net/play.html?p=b961d4d95a01648468a05cb440e964dc

In this game there's three levels. A checkpoint is set when the player's halfway across the first level, and the level is won when the player reaches the end. Instead of loading the next two levels, you just play the first level (from the checkpoint) twice more and then the game ends.

**Comment by eneb** [comment]
This isn't just an issue with the win command, if you win via WinConditions this still happens.

**Comment by increpare** [comment]
Should be fixed now. Thanks for the report. (may need a forcible refresh in your browser to update)

**Comment by eneb** [comment]
Fixed for me - thank you!

**Comment by chz16** [comment]
This seems to still happen with exported games. The test case in the opening post demonstrates it too, works fine from the puzzlescript.net player but exporting it from the editor and playing that results in the bug. Behavior replicates for me in Safari, Chrome, and Firefox on Mac.

**Comment by increpare** [comment]
blah! good catch.

**Comment by increpare** [comment]
ok, refresh - it should work now?

**Comment by chz16** [comment]
Yep, that did the trick. Thanks!

**Comment by increpare** [comment]
thanks for reporting it :)

**Comment by chz16** [comment]
Lukas Schüller just found that if you hit the checkpoint, reload the tab, and then continue the game from the checkpoint, the bug still happens. I verified this happens in both puzzlescript.net and exported games. This thing won't die. :(

**Comment by increpare** [comment]
blaaaaaa I'll look at it later

**Comment by increpare** [comment]
(thanks for the update... :'( )

**Comment by increpare** [comment]
can't repro this - did I magically fix it?
